### ISSUE TITLE
책상 구매하기

### ISSUE THREAD

**Issue by jungkoo** [jungkoo/notes#1]
### 1.1 책상 : 24만원 
* 크기 1500 x 760
http://mall.hanssem.com/goods/goodsDetailMall.do?gdsNo=696351
![image](https://user-images.githubusercontent.com/2881314/75510134-48d26e80-5a2d-11ea-9195-5501a4241189.png)

### 1.2 한샘매장상품 PLEX2 일반책상 1500_D60 : 17만원
http://mall.hanssem.com/goods/goodsDetailMall.do?gdsNo=696347
![image](https://user-images.githubusercontent.com/2881314/75513014-b505a000-5a36-11ea-8541-7f2642f9c6c9.png)

### 1.3 한샘매장상품 PLEX2 일반책상 1200_D76 : 16만원
http://mall.hanssem.com/goods/goodsDetailMall.do?gdsNo=696344

![image](https://user-images.githubusercontent.com/2881314/75512915-4cb6be80-5a36-11ea-8a18-c7c853c82664.png)

###  2.1 아르코 1876 데스크 : 15.7만원
* 크기 1800 x 760
http://www.dodot.co.kr/shop2/view.php?goods_id=11061&catype=0&vcate1=&vcate2=&vcate3=&mainSearch=아르코1
![image](https://user-images.githubusercontent.com/2881314/75510198-7ddec100-5a2d-11ea-9b39-a000c0e4d2c3.png)

### 2.2 아르코 1476  / E1
* 크기 1400 x 760 : 13.7만원
http://www.dodot.co.kr/shop2/view.php?goods_id=11059&catype=0&vcate1=&vcate2=&vcate3=&mainSearch=아르코
![image](https://user-images.githubusercontent.com/2881314/75510293-d1510f00-5a2d-11ea-97f7-8fb837bd1d77.png)

### 2.3 아르코 1246 / E0
* 11.5만
http://www.dodot.co.kr/shop2/view.php?goods_id=27280&catype=0&vcate1=&vcate2=&vcate3=&mainSearch=%EC%95%84%EB%A5%B4%EC%BD%94
![image](https://user-images.githubusercontent.com/2881314/75512862-209b3d80-5a36-11ea-8bd7-bab427d6a8f8.png)

### 2.4 콰트로 1606G / 10만 5천원

http://www.dodot.co.kr/shop2/view.php?goods_id=59
![image](https://user-images.githubusercontent.com/2881314/75552514-cde37500-5a79-11ea-85ce-8a2396673d37.png)

### 2.5 추가구성
* 4단 서랍장 : 13만원
http://www.dodot.co.kr/shop2/view.php?goods_id=31345&catype=0&vcate1=&vcate2=&vcate3=&mainSearch=아르코
![image](https://user-images.githubusercontent.com/2881314/75510359-1117f680-5a2e-11ea-8438-cf8b273ea7d0.png)

**Comment by AhnSeongHyun** [comment]
저는 두닷 쓰고 있습니다.

**Comment by jungkoo** [comment]
@AhnSeongHyun 
재택근무가 다음주까지 연장되서 급하게 주문함.
2.4 콰트로 1606G / 10만 5천원

**Comment by jungkoo** [comment]
@AhnSeongHyun 
여자친구꺼는 두닷껄로 사서 조립했는데... 
미즌하임꺼 보다 두닷꺼가 조립해보니 합이 잘맞네요. 

모니터랑 이거저거 올리려면 두닷이 기둥도 두껍고 좋아보임.
신학기 세일인가 뭔지 모르지만  세일할때  적림금 3천원쓰고 136,000에 구입했는데
괜찮네요


http://www.dodot.co.kr/shop2/view.php?goods_id=11060
